### PR TITLE
Enabled select list to save values on change

### PR DESCRIPTION
**Pull request by chalettu**
Fix for https://github.com/ManageIQ/manageiq-ui-classic/issues/3405
@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes

### CODE REVIEW

**Comment by chalettu** [comment]
@eclarizio would you mind taking a look and reviewing?

**Comment by miha-plesko** [comment]
I confirm this PR resolves the issue with dropdowns not storing selected value.

**Comment by himdel** [comment]
LGTM, `pfSelect` only supports `on-select` in angular-patternfly 4, not 3.

@chalettu Have you tested this in SUI? Just to make sure pf4 does still support ng-change :)

**Comment by chalettu** [comment]
Tested the issue in SUI and it works as expected.

**Comment by himdel** [comment]
Backported to `gaprindashvili` branch:

```
commit b41d00f86655f9b8f6ce3bc6c1e12bb18262c86c (HEAD -> gaprindashvili)
Author: Martin Hradil <himdel@seznam.cz>
Date:   Fri Feb 16 15:30:49 2018 +0000

    Merge pull request #258 from chalettu/selectValuesFix
    
    Enabled select list to save values on change
    
    (cherry picked from commit 22c58e77a77fdc78085b23adfaec74ecd6292fe5)
```

**Comment by himdel** [comment]
Released in 1.0.15, and 1.1.6.

**Comment by himdel** [comment]
Did *not* create a ui-classic PR to update gaprindashvili to 1.0.15 - this will need a BZ and a blocker label, right?

**Pull request merged**
