### PR TITLE
Remove typings dependencies

### PR DESCRIPTION
**Pull request by karelhala**
Since we are using typescript 2 we don't need to use typings (we should stop using them and move to supported @types at npm [future of declarative files](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/))

When using new module we have to add it to `webpack.config.js` to externals object:
```javascript
{"nameWeUseInApp": "nameOfLirary"}
```
Great example is lodash, `window` object has lodash stored as `_`, but when loading this module we want to call `lodash` (`import * as _ from 'lodash'` looks better than `import * as _ from '_'`).

### CODE REVIEW

**Comment by karelhala** [comment]
@himdel sorry I had to add `bower` back to install process, because we still use `angular-patternfly` from bower and tests were failing.

@himdel @mtho11 what do you think? Removing bower in this PR or follow up? Removing means installing `angular-patternfly` via NPM and adding all dependent packages to `vendor.js` file.

**Comment by himdel** [comment]
> @himdel sorry I had to add bower back to install process, because we still use angular-patternfly from bower and tests were failing.

No problem with bower in the install process, as long as it doesn't get run when installing `ui-components` into another repo :).

**Comment by karelhala** [comment]
I tweaked with build process even further and now we don't need bower dependencies anymore. Installing MPM package, adding it to `vendor.ts` and using it in code is sufficient.

**Comment by mtho11** [comment]
@karelhala IMO: it's probably best to remove bower in a separate PR

**Comment by karelhala** [comment]
> @karelhala IMO: it's probably best to remove bower in a separate PR

Ok, I'll rebase those 2 last commits and once this PR is closed I will open new one with just removing bower.

**Comment by karelhala** [comment]
@himdel @mtho11 re based so now it just removes typings, just wait after https://github.com/ManageIQ/ui-components/pull/42 is merged.

**Comment by martinpovolny** [comment]
Shall we wait for #43 ?

**Comment by karelhala** [comment]
@himdel @mtho11 @himdel rebased and fixed all problems. After this PR it's better to remove `node_modules` and `typings` file and re-run `npm install`.

I have created new issue so hopefully someone outside merge process who installed this project before this removal can see it https://github.com/ManageIQ/ui-components/issues/53.

**Comment by mtho11** [comment]
@himdel I see no reason why this shouldn't be merged?

**Comment by himdel** [comment]
@karelhala this PR broke `npm install`, for some reason it now fails with

```
...
Child extract-text-webpack-plugin:
        + 2 hidden modules
module.js:471
    throw err;
    ^

Error: Cannot find module 'node-uuid'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/nodejs/request/index.js:29:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17
npm ERR! Linux 4.8.0-2-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! manageiq-ui-components@0.0.11 prepublish: `webpack && npm run install-vendor`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the manageiq-ui-components@0.0.11 prepublish script 'webpack && npm run install-vendor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the manageiq-ui-components package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack && npm run install-vendor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs manageiq-ui-components
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls manageiq-ui-components
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/himdel/ui-components/npm-debug.log
```


It works fine without this PR.

**Comment by himdel** [comment]
... aah, because `npm run` is ..weird :)

Running `webpack && npm run install-vendor` works just fine, but `npm run install-vendor` fails.

That's the usual problem of npm run running stuff in a different environment..

**Pull request merged**
