### PR TITLE
Track by $index ensures no duplicates in select list

### PR DESCRIPTION
**Pull request by AllenBW**
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1558271

### proof, cuz people like that 🐰 
pfselect

### CODE REVIEW

**Comment by AllenBW** [comment]
@miq-bot add_label bug, blocker

**Comment by AllenBW** [comment]
@miq-bot add_labe gaprindashvili/yes

**Comment by AllenBW** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by himdel** [comment]
Nice catch @AllenBW :+1: :)

Verified single selects are unaffected in ops, and fixed by this in SUI.
TODO: ... multi ...

**Comment by himdel** [comment]
Backported to gaprindashvili:

```
commit 4ca33b653e291ee6483ed0f43caabd20406a6d3a (HEAD -> gaprindashvili)
Author: Martin Hradil <himdel@seznam.cz>
Date:   Thu Mar 29 11:47:08 2018 +0200

    Merge pull request #275 from AllenBW/bz/#1558271-boostrap-select-duplicate-values
    
    Track by $index ensures no duplicates in select list
    
    (cherry picked from commit 309c0047501df6f3b9a173d8ccc1e752407ea66d)
```

**Comment by himdel** [comment]
Released in 1.0.21, and 1.1.10.

**Pull request merged**
