### PR TITLE
New pagination

### PR DESCRIPTION
**Pull request by karelhala**
## Fixes  Pivotal [#146518283](https://www.pivotaltracker.com/story/show/146518283)
As requested before pagination should be much more responsive based on width of user's screen.

It also aligns pagination more to PF new design of [pagination](http://www.patternfly.org/pattern-library/navigation/pagination/) 

### Before
selection_181

### After
selection_180

### CODE REVIEW

**Comment by karelhala** [comment]
@serenamarie125 @epwinchell ping
Can you guys from UX review this? PF's version of pagination does not have select all and sort by option, so I had to squeeze them in, so verify if it's OK to have them there or not.

**Comment by karelhala** [comment]
@himdel what do you think, should I add option for the pagination to be sticky at bottom or we will just position it post render? This is question for UX team as well - pagination is by default above table/grid/..., but there is no settings to make it sticky at bottom of page.

**Comment by serenamarie125** [comment]
@himdel @karelhala Would like pagination sticky at the bottom

**Comment by serenamarie125** [comment]
@karelhala Can you send me a picture of what your entire view would look like?  Is this for tables or lists or any type of view?

**Comment by karelhala** [comment]
@serenamarie125 any type of view, current (non-sticky) looks like this (demo environment):

selection_184
selection_183
selection_182

I will try to make it sticky and test it in MiQ environment so we will see how it behaves.

**Comment by epwinchell** [comment]
https://www.pivotaltracker.com/n/projects/1613907/stories/146518283

**Comment by epwinchell** [comment]
@karelhala @serenamarie125 @dclarizio  I'd suggest moving the "items per page" bit over to the right like we used to have it - something like this:

screen-shot-2017-08-02-at-11 00 56-am

Also, it still needs some responsiveness work, which I can help with in this PR or in a follow-up.  

On the OPS UI side, it now shows both the # of pages and "x-xx of xxx (items)" - Can ditch the latter?
screen shot 2017-08-02 at 11 15 09 am

**Comment by himdel** [comment]
@karelhala Sticky would be great, except for mobile.. 

But maybe the pagination component should not care where you stick it, and just do the thing.

I'm guessing we'd be putting it inside `paging_div` in manageiq..

(Or an alternative is to say there won't be any of the old `paging_div` on gtl screens, and rely purely on css, but.. I'm almost sure we have screens with gtl which are forms, so the pagination component needs to be able to live in the same toolbar as the form buttons...)

**Comment by karelhala** [comment]
@epwinchell I'll update this PR with your changes. Do you want push rights to this branch so you can tweak the responsibility?

**Comment by epwinchell** [comment]
@karelhala Sounds good

**Comment by epwinchell** [comment]
@miq-bot add_label wip

**Comment by serenamarie125** [comment]
I think the paging should be sticky on the bottom.
I don't feel that the select all nor the sorting should be at the bottom.  I don't see a connection between paging with the sort/select all.

**Comment by epwinchell** [comment]
@serenamarie125 The paging is only at the top for the demo pages in UI-components. Also, the screenshots are out of date. This is how it currently looks (now using the new PF pagination styling)  on the UI-Comp demo pages:
screen shot 2017-08-10 at 10 46 35 am
screen shot 2017-08-10 at 10 46 26 am
screen shot 2017-08-10 at 10 46 14 am

This is how the updates (using the new PF pagination code) in this PR appear in the Ops UI:
screen shot 2017-08-10 at 10 40 26 am

I agree about moving sort/select Any suggestions on where we would put/style those?
cc/ @dclarizio

**Comment by serenamarie125** [comment]
@miq-bot add_label ux/approved

**Comment by serenamarie125** [comment]
Paging LGTM for this PR.  Thanks for doing this @karelhala !

**Comment by epwinchell** [comment]
@miq-bot assign @himdel

**Comment by epwinchell** [comment]
@miq-bot rm_label wip

**Comment by epwinchell** [comment]
@himdel @karelhala I think both of these PRs are ready to be merged

**Comment by himdel** [comment]
@epwinchell @karelhala .. there's a bug :)

Go to `/container_project/show_list`...

evil

**Comment by epwinchell** [comment]
@himdel Looks fine to me:

screen shot 2017-08-29 at 9 20 41 am

**Comment by himdel** [comment]
Ok, never mind then :) I've only seen it once, if I can reproduce again, I'll try to get more info.

**Pull request merged**
