### PR TITLE
Corrected docstirng for dialogUser component

### PR DESCRIPTION
**Pull request by romanblanco**
Updating docsctring example for using dialogUser component after changes in https://github.com/ManageIQ/ui-components/pull/100

@chalettu please take a look if it's OK

### CODE REVIEW

**Comment by chalettu** [comment]
Looks good to me.  Good catch.  We renamed the component and I guess I missed the docs.

**Comment by chalettu** [comment]
Hey @romanblanco .  I think we might close this one. I took your changes from this one and already included them in an impending PR that rolls up some other changes to the dialog component

**Comment by chriskacerguis** [comment]
PR that @chalettu is referencing: https://github.com/ManageIQ/ui-components/pull/117

**Comment by romanblanco** [comment]
@chalettu Cool, thanks 👍

**Pull request closed without merging**
