### PR TITLE
Validate presence of category attribute for Tag Control dialog field

### PR DESCRIPTION
**Pull request by romanblanco**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1507754

### CODE REVIEW

**Comment by ohadlevy** [comment]
@karelhala mind having a look? thanks!

**Comment by JPrause** [comment]
@ohadlevy since this resolves a blocker issue, would you be able to merge this PR.

**Comment by romanblanco** [comment]
@miq-bot add_label blocker
@miq-bot add_label gaprindashvili/yes
@miq-bot add_label bug

**Comment by himdel** [comment]
@miq-bot add_label gaprindashvili/backported
@miq-bot remove_label gaprindashvili/yes

This was released in manageiq-ui-components 1.0.6, backported to gaprindashvili via ManageIQ/manageiq-ui-classic#3269.

**Pull request merged**
