### PR TITLE
Fixed issue where options were being duplicated in dialogs

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label gaprindashvili/yes
@miq-bot add_label bug
Fix for BZ # https://bugzilla.redhat.com/show_bug.cgi?id=1598455

### CODE REVIEW

**Comment by eclarizio** [comment]
@martinpovolny I don't have merge rights so I don't know if I should be the one assigned 😢

**Comment by JPrause** [comment]
@miq-bot add_label blocker

**Comment by himdel** [comment]
Backported to gaprindashvili:

```
commit bd9a88a6a4905092a27c9791534f7767bc2b0fa2 (HEAD -> gaprindashvili)
Author: Dan Clarizio <dclarizi@redhat.com>
Date:   Fri Jul 13 07:53:14 2018 -0700

    Merge pull request #316 from chalettu/dialog-duplicate-values
    
    Fixed issue where options were being duplicated in dialogs
    
    (cherry picked from commit 01a083c1c79ffca636d904fc8639494b90043f73)
```

@miq-bot add_label gaprindashvili/backported
@miq-bot remove_label gaprindashvili/yes

**Comment by himdel** [comment]
[gaprindashvili] Released as 1.0.32

**Pull request merged**
