### PR TITLE
Bower cleanup

### PR DESCRIPTION
**Pull request by himdel**
This PR removes any bower support and references.

It also changes what happens on PR merge:

* before, the `bower-dev` branch was updated with the current state
* now, the `bower-dev` branch will stay on the last version used by ui-classic via bower (already added a notice to the readme [there](https://github.com/ManageIQ/ui-components/tree/bower-dev#angular-ui-components-for-manageiq)) and ui-classic will use current npm version

(related to https://github.com/ManageIQ/manageiq-ui-classic/pull/4694 and https://github.com/ManageIQ/manageiq-ui-classic/pull/4735 but does not depend on either)

### CODE REVIEW

**Comment by himdel** [comment]
Cc @romanblanco, @eclarizio, @chalettu, @skateman (because you're the ones who usually fix stuff here)

This change would mean that you may need to update the `@manageiq/ui-components` dependency in ui-classic and ui-service manually, as it will no longer follow master.

Any issues with that?

**Comment by skateman** [comment]
Hmm...seems okay to me, good job :+1:

**Comment by eclarizio** [comment]
@himdel Seems fine to me, can we put instructions on how to update the dependency manually here/somewhere for reference? I'm pretty sure it's just a symlink, but I did mine a long time ago and don't remember if there are other steps.

**Comment by himdel** [comment]
Oh, once a PR is merged (and autorelease (#351) is working), you will just need a `yarn add @manageiq/ui-components` in the right repo to upgrade to the current version.

For development there's `yarn link`, added to https://github.com/ManageIQ/ui-components/wiki :).

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit a297544662d70691a3d2b8a84a8b1df0b346b7e7
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Oct 16 09:29:06 2018 -0400

    Merge pull request #349 from himdel/bower-cleanup
    
    Bower cleanup
    
    (cherry picked from commit 4e1eb302a99cac84bccaa15a55d195653e4849cc)
```

**Pull request merged**
