### PR TITLE
Add support message for regex

### PR DESCRIPTION
**Pull request by akhilkr128**
[issue](https://github.com/ManageIQ/manageiq/issues/21567)

Screenshot 2022-03-28 at 5 06 24 PM
Screenshot 2022-03-28 at 5 06 24 PM

Before merging this one, we need to merge this [PR](https://github.com/ManageIQ/manageiq-schema/pull/643).

Dependent PRs
-----------------
https://github.com/ManageIQ/manageiq/pull/21792
https://github.com/ManageIQ/manageiq-schema/pull/643

### CODE REVIEW

**Comment by Fryguy** [comment]
@kavyanekkalapu Are these components still used in the classic ui, or is it only for the service ui?

**Comment by akhilkr128** [comment]
@Fryguy / @kavyanekkalapu I think ui-classic is taking the below components from ui-components. Please correct me if I am wrong.

Screenshot 2022-04-08 at 1 58 53 PM

**Comment by kavyanekkalapu** [comment]
@akhilkr128 We are using dialog editor ( files you edited ) . I don't think we are using few from above screenshot. i will check and delete those components.

**Comment by kavyanekkalapu** [comment]
cc @jeffibm please test

**Pull request merged**
