### PR TITLE
Add tree persistence support for TreeSelectorComponent

### PR DESCRIPTION
**Pull request by skateman**
Forgot this feature earlier :disappointed:

### CODE REVIEW

**Comment by martinpovolny** [comment]
So what is this supposed to do? And where are the tests?

**Comment by skateman** [comment]
@martinpovolny it passes the `persist` argument to the underlying [`treeView`](https://github.com/ManageIQ/ui-components/blob/master/src/tree-view/treeViewComponent.ts#L76) component. For now we don't need it but wanted to keep the two components symmetric as possible. Not sure how and why should I test a trivial angular feature (i.e. passing bindings) that's being provided by the framework. I'm working on some tests for both components, but other things first ...

**Comment by martinpovolny** [comment]
@skateman : ok, I saw nothing but the passing of the argument and I was unsure because of "brief" description.

**Comment by skateman** [comment]
@martinpovolny sorry, I thought it's trivial as it is a symmetric feature...

**Pull request merged**
