### PR TITLE
Fix radio button styling

### PR DESCRIPTION
**Pull request by epwinchell**
Remove button styling from radio buttons 

Issue: #330

Before:
screen shot 2018-07-25 at 12 20 09 pm
screen shot 2018-07-25 at 12 20 26 pm

After

screen shot 2018-07-25 at 12 07 58 pm
screen shot 2018-07-25 at 12 07 37 pm

### CODE REVIEW

**Comment by epwinchell** [comment]
@miq-bot assign @himdel

**Comment by epwinchell** [comment]
@miq-bot add_reviewer @terezanovotna

**Comment by epwinchell** [comment]
@miq-bot add_label gaprindashvili/no, formatting/styling

**Comment by epwinchell** [comment]
@miq-bot rm_label wip

**Comment by himdel** [comment]
LGTM, waiting for `ux/approved` :)

**Comment by terezanovotna** [comment]
@miq-bot remove_label ux/review
@miq-bot add_label ux/approved

**Pull request merged**
