### PR TITLE
styling reorganization

### PR DESCRIPTION
**Pull request by epwinchell**
This PR is the initial pass at reorganization and annotation of the stylesheet. It also renames "mig-*" prefixed classes to "miq-*"

### CODE REVIEW

**Comment by epwinchell** [comment]
@miq-bot technical debt, formatting/styling

**Comment by epwinchell** [comment]
@karelhala Please review

**Comment by epwinchell** [comment]
@miq-bot assign @karelhala

**Comment by epwinchell** [comment]
@miq-bot add_label technical debt, formatting/styling

**Comment by martinpovolny** [comment]
@epwinchell : you don't like MIGs? ;-)

**Comment by epwinchell** [comment]
xcropped-mig-29-icon-1-32x32 jpg pagespeed ic wjtsyqhgoc

**Comment by karelhala** [comment]
Looks good, both in demo and in MiQ application. Everything should be fine and working, so @himdel want to test it by yourself, if not, I guess we can merge this.

**Comment by epwinchell** [comment]
@miq-bot assign @himdel

**Comment by himdel** [comment]
So.. uh, I don't see any difference? Is that intended?

So.. can you maybe add some screenshots if there is supposed to be a difference?

**Pull request merged**
