### PR TITLE
Past days selection in date control fields corrected

### PR DESCRIPTION
**Pull request by romanblanco**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1464243

datepicker component: https://github.com/angular-ui/bootstrap/tree/master/src/datepicker

### CODE REVIEW

**Comment by romanblanco** [comment]
@chalettu please, take a look

**Comment by martinpovolny** [comment]
ping @chalettu ?

**Comment by martinpovolny** [comment]
@eclarizio, @chalettu : Do you have a moment to review this one, please?

**Comment by romanblanco** [comment]
> change the name of allowPastDays to something like setPastDate, setMinDate, setAllowablePastDays or something like that because the name allowPastDays reads to me like it's going to enable past dates by setting a boolean but it actually sets either null or today's date.

makes sense. changing to `setMinDate`. Thanks @eclarizio!

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 36d6a1a7943e4ae6650eac022012c3738fe70019
Author: Martin Povolny <mpovolny@redhat.com>
Date:   Mon Nov 12 12:38:04 2018 +0100

    Merge pull request #355 from romanblanco/bz1464243
    
    Past days selection in date control fields corrected
    
    (cherry picked from commit c17d2aa45943a69151a44c4c6773c6ac872c3a34)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1464243
```

**Pull request merged**
