### PR TITLE
Use miq-select in dialogUser's tagging fields

### PR DESCRIPTION
**Pull request by skateman**
Making it consistent with the dropdowns and making a step towards fixing https://github.com/ManageIQ/manageiq-ui-classic/issues/6392 and making https://github.com/ManageIQ/manageiq-ui-classic/pull/6400 less buggy.

@miq-bot assign @himdel

### CODE REVIEW

**Comment by skateman** [comment]
Not sure if the issue is in the dialog user or in my https://github.com/ManageIQ/manageiq-ui-classic/pull/6400, but there's no test for the tag control in this repo:
Peek 2019-11-13 08-55

Somehow the click handling is doing weird stuff :confused:

**Comment by skateman** [comment]
bump

**Comment by himdel** [comment]
What *is* the click handling issue? Do we have an issue somewhere?

Or can you describe what's happening in the video?

**Comment by skateman** [comment]
@himdel if you try to select more and more items, it behaves like on the gif. The first one remains selected, the rest gets deselected.

**Comment by himdel** [comment]
Aah, thanks :) I wasn't sure when the clicks came.

Looking.. :)

**Comment by himdel** [comment]
That issue is only happening together with ManageIQ/manageiq-ui-classic#6400, so this one should be safe to merge.

**Comment by simaishi** [comment]
Backported to ivanchuk via https://github.com/ManageIQ/ui-components/pull/446

**Pull request merged**
