### PR TITLE
Fixed issue dialog component with fields not refreshing data appropriately

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label bug

### CODE REVIEW

**Comment by chalettu** [comment]
@eclarizio , here is that PR we discussed.  Let me know if you think we left anything out.

**Comment by eclarizio** [comment]
@chalettu Looks good to me 👍 , thanks for the help debugging this haha, what a pain.

**Comment by chalettu** [comment]
@himdel , can you take a look at this PR when you have a sec and approve?  We also need to request a push to NPM and bower of this update.

**Comment by himdel** [comment]
Aand released `@manageiq/ui-components` 0.0.23 :)

**Pull request merged**
