### PR TITLE
Corrected displaying of default value in Dialog Editor preview

### PR DESCRIPTION
**Pull request by romanblanco**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1531316

issue was introduced in commit 9245795638b338b7fb5898a9ee9d407543b0bda4

### CODE REVIEW

**Comment by romanblanco** [comment]
@miq-bot add_label gaprindashvili/yes
@miq-bot add_label blocker

**Comment by romanblanco** [comment]
How to test:

screencast from 2018-01-19 20-17-43

_i was using TrackPoint to record this, sorry :D_

**Comment by himdel** [comment]
LGTM, fixes the `modalData` vs `fieldData` typo, adds "None" as an option for single-value dropdowns.

**Comment by himdel** [comment]
@miq-bot add_label gaprindashvili/backported
@miq-bot remove_label gaprindashvili/yes

This was released in manageiq-ui-components 1.0.8, backported to gaprindashvili via ManageIQ/manageiq-ui-classic#3304.

**Pull request merged**
