### PR TITLE
i18n string extraction & friends

### PR DESCRIPTION
**Pull request by mzazrivec**
What this PR does:
* use `angular-gettext-cli` to extract strings from javascript sources & html markup
* remove extraneous `translate` directive
* add `locale/` subdirectory with `ui-components.pot` catalog
* add gettext catalog validation
* add `zanata.xml`

### CODE REVIEW

**Comment by mzazrivec** [comment]
@himdel review please?

**Comment by himdel** [comment]
LGTM :)

Should these 2 go in gaprindashvili?

**Comment by mzazrivec** [comment]
> Should these 2 (#320 and #322) go in gaprindashvili?

Yes, although for gaprindashvili I'll have to update change version in zanata.xml (I'll do that in a separate PR).

**Comment by himdel** [comment]
Backported to gaprindashvili:

```
commit 778b2d1f7c128f7ff3072c6f945a35be84f82fbf
Author: Martin Povolny <mpovolny@redhat.com>
Date:   Wed Jul 18 17:01:50 2018 +0200

    Merge pull request #320 from mzazrivec/i18n_string_extraction
    
    i18n string extraction & friends
    
    (cherry picked from commit 81a8f592a3e3a79a0f972bfb91bade44f2ebc9a7)
```

@miq-bot add_label gaprindashvili/backported
@miq-bot remove_label gaprindashvili/yes

**Comment by ZitaNemeckova** [comment]
Released in v1.0.33
https://github.com/ManageIQ/manageiq-ui-service/pull/1464
https://github.com/ManageIQ/manageiq-ui-classic/pull/4352

**Pull request merged**
