### PR TITLE
Mark numeral.js as an external dependency provided by ui-classic

### PR DESCRIPTION
**Pull request by skateman**
@karelhala asked @karelhala gets it, we want this as a dependency in ui-classic.

### CODE REVIEW

**Comment by himdel** [comment]
Makes sense.. but.. where is this being used and is *that* used in SUI?

**Comment by skateman** [comment]
@himdel, we introduced this with [quadicons](https://github.com/ManageIQ/ui-components/pull/243/commits/356c37f451244589600fc79545a0ba1590efa046) for number abbreviations. I don't think SUI is already depending on it :wink:

**Comment by himdel** [comment]
Perfect.. so now only the failing specs.. :)

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  ReferenceError: Can't find variable: numeral
  at dist/js/ui-components.js:9
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  ReferenceError: Can't find variable: numeral
  at src/common/filters/abbrNumberFilter.spec.ts:74
```

.. looks like numeral is missing from `package.json`? :)

**Comment by skateman** [comment]
@karelhala need some help here

**Comment by karelhala** [comment]
@skateman update `src/vendor.ts` to add `numeral` as global package. Otherwise webpack will try to include it to the final build, but tests are trying to find them at window.

```diff
diff --git a/src/vendor.ts b/src/vendor.ts
index 30ac03d..8c84839 100644
--- a/src/vendor.ts
+++ b/src/vendor.ts
@@ -13,4 +13,6 @@ import 'angular-dragdrop';
 import 'angular-bootstrap-switch';
 import 'ui-select';
 import 'patternfly-bootstrap-treeview';
-import 'numeral';
+import * as numeral from 'numeral';
+
+window['numeral'] = numeral;
```

**Comment by skateman** [comment]
@himdel now it should be fine!

**Pull request merged**
