### PR TITLE
gtl list - Add is-checkbox-cell class to td with checkbox

### PR DESCRIPTION
**Pull request by himdel**
..which the [corresponding ui-classic PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/3207) will use to detect misclicks around the checkbox

### CODE REVIEW

**Comment by himdel** [comment]
Ping @karelhala :) can you merge?

**Comment by himdel** [comment]
gaprindashvili BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1627387

**Comment by JPrause** [comment]
@miq-bot add_label blocker

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 030c174cb5749f9c93c1fcee80b206627d1e752b
Author: Karel Hala <ch4rlien@gmail.com>
Date:   Wed Feb 7 13:26:37 2018 +0100

    Merge pull request #230 from himdel/is-checkbox-cell
    
    gtl list - Add is-checkbox-cell class to td with checkbox
    (cherry picked from commit 12dcdf28cf66e8fd66b63adef5d3717c4a7fa41b)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1629094
```

**Pull request merged**
