### PR TITLE
Fix for dynamic dialog fields not being updated 

### PR DESCRIPTION
**Pull request by romanblanco**
Using dialogField.value for fields that are not a subclass of `DialogFieldSortedItem`.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1696474

### CODE REVIEW

**Comment by romanblanco** [comment]
@d-m-u or @eclarizio, could you verify the fix works?

**Comment by romanblanco** [comment]
@miq-bot add_label bug, hammer/yes

**Comment by h-kataria** [comment]
@himdel @martinpovolny can you please merge this PR

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 7bca0ba748ef1cb0ad73d80b2ab143ca71b57ae6
Author: Martin Povolny <mpovolny@redhat.com>
Date:   Wed Apr 10 18:52:25 2019 +0200

    Merge pull request #381 from romanblanco/bz1696474
    
    Fix for dynamic dialog fields not being updated
    
    (cherry picked from commit a9c4a08d4856dcde41839260f2db91fddee74777)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1698586
```

**Comment by d-m-u** [comment]
Can we change https://github.com/ManageIQ/ui-components/blob/7bca0ba748ef1cb0ad73d80b2ab143ca71b57ae6/src/dialog-user/services/dialogData.ts#L140 to use the value rather than the default_value?

**Comment by himdel** [comment]
@d-m-u So, something like..

```
let fieldValue = (value !== undefined) ? value : ((field.value !== undefined) ? field.value : field.default_value);
```

?

**Comment by h-kataria** [comment]
@romanblanco cc

**Pull request merged**
