### PR TITLE
Fix Dialog Editor styling issues

### PR DESCRIPTION
**Pull request by epwinchell**
This PR is a follow-up to https://github.com/ManageIQ/manageiq-ui-classic/pull/3668 and addresses the following requests:

-  correctly applies form-horizontal class for label positioning
-  decrease size of label column 
-  increase size of text area
-  decrease size of dropdowns
-  move refresh button below text area

https://bugzilla.redhat.com/show_bug.cgi?id=1553697

Old (Classic UI)
screen shot 2018-03-27 at 2 22 15 pm

New (Classic UI)
screen shot 2018-03-27 at 2 20 51 pm

Old (Classic UI)
screen shot 2018-05-02 at 12 55 48 pm

New (Classic UI)
screen shot 2018-05-03 at 10 25 26 am

Old (Service UI)
screen shot 2018-04-11 at 1 38 03 pm

New (Service UI)
screen shot 2018-04-11 at 1 07 21 pm

### CODE REVIEW

**Comment by epwinchell** [comment]
@miq-bot add_label bug, gaprindashvili/yes

**Comment by epwinchell** [comment]
@miq-bot assign @himdel

**Comment by epwinchell** [comment]
@himdel pls test

**Comment by himdel** [comment]
LGMT, the html structure looks good, not seeing any breakage in ops or sui :+1:

**Comment by himdel** [comment]
Backported to gaprindashvili:

```
commit 0fbe9eecd89762b03889adcd7730225164fd6ce9 (HEAD -> gaprindashvili)
Author: Martin Hradil <himdel@seznam.cz>
Date:   Fri May 18 16:02:00 2018 +0200

    Merge pull request #293 from epwinchell/dialog_editor_updates2
    
    Fix Dialog Editor styling issues
    
    (cherry picked from commit 268a2f69889d671ffef418bd4628778cd2914b4e)
```

@miq-bot add_label gaprindashvili/backported
@miq-bot remove_label gaprindashvili/yes

**Pull request merged**
