### PR TITLE
Fixed bugs with dialog field validations

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label bug

### CODE REVIEW

**Comment by chalettu** [comment]
This PR addresses https://github.com/ManageIQ/ui-components/issues/178
https://github.com/ManageIQ/ui-components/issues/179
and https://github.com/ManageIQ/ui-components/issues/180 .  These issues were all inter related which is why I decided to combine into one PR

**Comment by chalettu** [comment]
Screen shot of scenario that involves a email address that has a regex but is not required. 
We would expect the shopping cart button to be enabled if email is blank, but if its invalid make sure its disabled. This scenario also shows the email regex working as expected.  
email_validation

**Comment by chalettu** [comment]
This screenshot addresses the issue with when a user requires a checkbox.  Requiring a checkbox mandates that the dialog is invalid if the user does not have the box checked.  
checkbox_fix

**Comment by Loicavenel** [comment]
Great.. thanks

**Comment by chriskacerguis** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1502314

**Pull request merged**
