### PR TITLE
Improved 'switch' statements implementation

### PR DESCRIPTION
**Pull request by romanblanco**
Updating `modalService` controller according to @karelhala's [suggestions](https://github.com/ManageIQ/ui-components/pull/139#discussion_r137266430)

Behaviour should not be changed

/cc @martinpovolny @karelhala

### CODE REVIEW

**Comment by martinpovolny** [comment]
@karelhala : ping

**Comment by romanblanco** [comment]
I've discussed some possible changes with @karelhala, but I'd leave it for next PR, and merge this one, if it's OK to be merged.

**Comment by karelhala** [comment]
@romanblanco looks good, except there are couple of tsling issues which are "just" warnings, but it's better to be fixed.
```
WARNING in ./src/dialog-editor/services/modal/modalService.ts
[63, 6]: Missing semicolon
[85, 10]: Missing semicolon
[140, 6]: Missing semicolon
```

**Comment by karelhala** [comment]
LGTM, merging.

**Pull request merged**
