### PR TITLE
[WIP] BZ#1539862- Added multiselect as a dropdown option type

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label ux/review
@miq-bot add_label bug

### CODE REVIEW

**Comment by chalettu** [comment]
Screenshot of intended interaction for multiselect for drop downs and tag controls
multiselect_demo

**Comment by chalettu** [comment]
@serenamarie125 , I wanted you to take a look and weigh in on this.  Our dialog component needs to support a tag control and a multiselect control as these are supported input types for dialogs in both SUI and Classic UI.  I am not sure what the usage pattern was for multiselect in Classic UI but this field type has not previously existed in SUI.  This control will be universal across both UI's.

**Comment by chalettu** [comment]
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1539862

**Comment by eclarizio** [comment]
It's a lot more obvious that this seems to be the wrong component since it's multi-select, I didn't realize before with the single `ui-select` component, but I think we should just be using standard select elements with the `pf-select` property on them to make them patternfly styled.

They should look like this:
screen shot 2018-02-02 at 1 18 11 pm
screen shot 2018-02-02 at 1 18 22 pm

(Found here: https://www.patternfly.org/pattern-library/widgets/#bootstrap-select)

@chalettu Do you know if there is a specific reason we're using `ui-select` instead of the patternfly select stuff?

**Comment by JPrause** [comment]
@chalettu was there further edits needed? This is for a blocker issue.

**Comment by chalettu** [comment]
@JPrause I am going to create a new PR that is updated with changes.  I will link this closed PR just for history sake

**Pull request closed without merging**
