### PR TITLE
Removed label and description of dialog from dialog-user

### PR DESCRIPTION
**Pull request by chalettu**
Fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1554259
@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes

### CODE REVIEW

**Comment by chalettu** [comment]
Before I removed the label and description fields.  
before

**Comment by chalettu** [comment]
After I removed the label and description fields. 
after

**Comment by chalettu** [comment]
@miq-bot add_label ux/review

**Comment by chalettu** [comment]
@serenamarie125 could you weigh in on this change.  It was requested that we remove the label for a service dialog as it was apparently not something that was originally in the classic UI.  Since dialogs are shared , this change effects SUI as well.  I removed both the title and description as I was thinking that the description out on its own probably has no context.  Please let me know your thoughts.  I took a SS of the before and after.

**Comment by serenamarie125** [comment]
@miq-bot add_label ux/approved

**Comment by serenamarie125** [comment]
@miq-bot add_labels ux/approved

**Comment by serenamarie125** [comment]
@miq-bot remove_labels ux/review

**Comment by himdel** [comment]
Backported to gaprindashvili:

```
commit fd4dbf0ef8edc21f39be08f2495fabde59a4d040 (HEAD -> gaprindashvili)
Author: Martin Povolny <mpovolny@redhat.com>
Date:   Thu Mar 15 08:17:14 2018 +0100

    Merge pull request #269 from chalettu/dialog-name
    
    Removed label and description of dialog from dialog-user
    
    (cherry picked from commit fe673cfce02898de20c22c26510330db220fa8bd)
```

@miq-bot add_label gaprindashvili/backported
@miq-bot remove_label gaprindashvili/yes

**Comment by himdel** [comment]
Released in 1.1.9 and 1.0.19

**Pull request merged**
