### PR TITLE
Set ng-change for tag control options

### PR DESCRIPTION
**Pull request by syncrou**
Create a function setupCategoryOptions to be called on ng-change

Gigantic Thank you to @eclarizio for all his help!

https://bugzilla.redhat.com/show_bug.cgi?id=1542590

### CODE REVIEW

**Comment by syncrou** [comment]
@miq-bot assign @eclarizio 

@miq-bot add_label blocker

**Comment by syncrou** [comment]
cc - @gmcculloug

**Comment by gmcculloug** [comment]
@miq-bot add_labels bug, gaprindashvili/yes

**Comment by syncrou** [comment]
@miq-bot assign @himdel

**Comment by syncrou** [comment]
@eclarizio - Please review

**Comment by eclarizio** [comment]
@romanblanco You may want to review this as well, figured I'd tag you since it's in the dialog editor section.

**Comment by romanblanco** [comment]
> Now, @syncrou made a change to the core repo to take all 3 properties into account

the mentioned change - https://github.com/ManageIQ/manageiq/pull/16965

**Comment by JPrause** [comment]
Is this blocker PR ready to merge?

**Comment by romanblanco** [comment]
@himdel @karelhala can you merge?

**Comment by himdel** [comment]
Backported to `gaprindashvili` branch:

```
commit e568c5807684477263682f093162b202599414a0 (HEAD -> gaprindashvili)
Author: Dan Clarizio <dclarizi@redhat.com>
Date:   Tue Feb 13 07:14:14 2018 -0800

    Merge pull request #253 from syncrou/set_tag_control_options_set
    
    Set ng-change for tag control options
    
    (cherry picked from commit c07afbc46a80fb846a2426f1e54726380c7a6290)
```

**Comment by himdel** [comment]
Released in 1.0.13

**Pull request merged**
