### PR TITLE
Remove code dealing with default value for Tag Control

### PR DESCRIPTION
**Pull request by romanblanco**
reaction on https://github.com/ManageIQ/ui-components/pull/414#issuecomment-528266646

### CODE REVIEW

**Comment by himdel** [comment]
I'm worried about what happens when you already select a value and have this field in the list of fields to refresh for another field.

And of dynamic `default_value` from automate, if that's possible for tag controls.

**Comment by romanblanco** [comment]
> and have this field in the list of fields to refresh for another field

Tag Control field can't be in a list of fields to refresh. It's not a refreshable field.

**Comment by himdel** [comment]
You're right, this should be fine. Merging :)

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 8de4907701969db5f3a1a71aa9d594590ef673a9
Author: Martin Hradil <mhradil@redhat.com>
Date:   Mon Sep 23 13:51:04 2019 +0200

    Merge pull request #415 from romanblanco/tag_ctrl_default_value

    Remove code dealing with default value for Tag Control

    (cherry picked from commit c9c805517a99a8d32263a531a1ad7a951c7b3b12)
```

**Pull request merged**
