### PR TITLE
Add image icon to toolbar simple buttons

### PR DESCRIPTION
**Pull request by karelhala**
When button has no icon, but image_url is present use this image_url instead of icon as img tag

### CODE REVIEW

**Comment by karelhala** [comment]
@mtho11 after mergin this and https://github.com/ManageIQ/ui-components/pull/13 please release new version of `ui-components`

**Comment by karelhala** [comment]
As proposed by @skateman and @himdel MiQ will move soon-ish to `patternfly-sass: 3.9.0`, this will break toolbars so they will show switching of views right next to toolbar elements. So I've updated toolbar-view component so we don't have to change anything after migrating to `3.9.0`

**Comment by himdel** [comment]
Verified that with new patternfly, the view toolbar buttons are correctly pulled right while `download_choice` remains on the left side.. :+1:

**Comment by himdel** [comment]
Available in 0.0.6

**Pull request merged**
