### PR TITLE
Fix Bithound badge error because of unexpected line break.

### PR DESCRIPTION
**Pull request by mtho11**
Unfortunately couldn't see this error until it was deployed to github.

### CODE REVIEW

**Comment by himdel** [comment]
I still can't see the difference :) .. but .. looking https://github.com/mtho11/ui-components/tree/badge_linebreak_error seems like it's still not quite fixed..

I wonder if it'd be easier to just use markdown like everywhere else..

**Comment by mtho11** [comment]
@himdel markdown is fine by me.

**Comment by himdel** [comment]
OK, can give me a second pair of eyes on https://github.com/himdel/ui-components/tree/markdown please?

**Comment by mtho11** [comment]
@himdel LGTM

**Pull request closed without merging**
