### PR TITLE
Remove CSS rule to hide help icon in dialog fields

### PR DESCRIPTION
**Pull request by romanblanco**
screencast from 2017-09-21 10-33-13

**Pivotal tasks**:

https://www.pivotaltracker.com/story/show/150614285
https://www.pivotaltracker.com/story/show/150614221

@chalettu can you take a look on this?

### CODE REVIEW

**Comment by Loicavenel** [comment]
@serenamarie125 can you review this one?

**Comment by chalettu** [comment]
Actually.  This was hidden on purpose because we are waiting on an API addition for field level help .  The description field is not the same as the new field that they will be adding.

**Comment by romanblanco** [comment]
@chalettu I've understood, that the _description_ should be just replaced by _help_, because the _description_ is not actually much used. Or do we want to have both _description_ and _help_ at the same time? @Loicavenel

**Comment by dclarizio** [comment]
@chalettu it's my understanding that @Loicavenel decided to re-use the `description` field to hold the online help text.  There was even a migration done to expand the length of text it can hold.
Will let Loic chime in to verify.

**Comment by himdel** [comment]
Looks like this just unhides the help, and updates the field which is currently being displayed.

Another PR depends on this, merging, we can always rename the field later.

**Pull request merged**
