### PR TITLE
Fix for default value on dropdown inside dialog not storing value

### PR DESCRIPTION
**Pull request by eclarizio**
This should fix the major issue with https://bugzilla.redhat.com/show_bug.cgi?id=1531316, but while testing I found another issue when using multi-value dropdowns, and to fix that, we will need [this PR](https://github.com/ManageIQ/manageiq/pull/16978) from the main repo.

@miq-bot add_label gaprindashvili/yes, bug, blocker
@romanblanco Please review
@miq-bot assign @himdel

### CODE REVIEW

**Comment by himdel** [comment]
@eclarizio Is this independent of https://github.com/ManageIQ/manageiq/pull/16978? At least in the sense that merging this one first won't break anything? :)

**Comment by eclarizio** [comment]
@himdel Correct. If this gets merged first then just the multi-select will continue to be broken. The main repo PR is required for multi-select to be fully fixed.

**Comment by himdel** [comment]
LGTM, seems like it matches the old order now :)

**Comment by himdel** [comment]
Backported to `gaprindashvili`:

```
commit a092277c5c7be7d27803a8cee997625e103e5c26 (HEAD -> gaprindashvili)
Author: Martin Hradil <himdel@seznam.cz>
Date:   Fri Feb 9 21:11:12 2018 +0000

    Merge pull request #250 from eclarizio/BZ1531316
    
    Fix for default value on dropdown inside dialog not storing value
    
    (cherry picked from commit e1c90f31dd1f0aad9191dc9a994c44015e403d63)
```

---

Released in `@manageiq/ui-components@1.1.2`, `@manageiq/ui-components@1.0.11`, and `manageiq-ui-components@1.0.11` (bower).

@miq-bot add_label gaprindashvili/backported
@miq-bot remove_label gaprindashvili/yes

**Pull request merged**
