### PR TITLE
Test that 'id' attribute is missing

### PR DESCRIPTION
**Pull request by romanblanco**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1578986

behaviour for `nil` attributes is changed in https://github.com/ManageIQ/manageiq-api/pull/253

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label blocker

**Comment by JPrause** [comment]
@romanblanco can you ping someone to review this PR. We're trying to get all blockers resolved quickly.

**Comment by romanblanco** [comment]
@chalettu could you do the review, please?

**Comment by JPrause** [comment]
@romanblanco appears we're good to go. Who can merge this PR?

**Comment by romanblanco** [comment]
@miq-bot assign @himdel

**Comment by romanblanco** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by chalettu** [comment]
Looks good to me

**Comment by ZitaNemeckova** [comment]
@miq-bot remove_label gaprindashvili/yes

**Comment by himdel** [comment]
Released in 1.0.31

**Pull request merged**
