### PR TITLE
Fix missing association drop down

### PR DESCRIPTION
**Pull request by romanblanco**
correction for bugs introduced in #170 

@eclarizio @himdel

### CODE REVIEW

**Comment by eclarizio** [comment]
Not that many people use it, but I noticed for `src/dialog-editor/components/modal-field-template/radio-button.html`, the association drop down is not there for dynamic ones.

Also, are you planning on putting that association drop down snippet of code back into another template file to be used in all of these places or is that a separate PR?

**Comment by romanblanco** [comment]
@eclarizio 

> Not that many people use it, but I noticed for src/dialog-editor/components/modal-field-template/radio-button.html, the association drop down is not there for dynamic ones.

Thanks, I'll update PR.

> Also, are you planning on putting that association drop down snippet of code back into another template file to be used in all of these places or is that a separate PR?

I do, also with other repeated fields, discussed it with @himdel, but I'll do it in separate PR

**Comment by eclarizio** [comment]
@romanblanco Sounds good 👍

**Comment by romanblanco** [comment]
@eclarizio I'm checking and it seems to work to me. Am I doing something wrong?

screencast from 2017-10-20 19-14-43

**Comment by eclarizio** [comment]
@romanblanco No, looks fine. I was just looking at the code and must've missed it. Sorry about that!

**Comment by martinpovolny** [comment]
@eclarizio : good to merge then?

**Comment by eclarizio** [comment]
@martinpovolny Good to go for me, yeah.

**Pull request merged**
