### PR TITLE
Make separators and toolbar list items hidable

### PR DESCRIPTION
**Pull request by karelhala**
@jzigmund proposed that toolbar separators and toolbar items could be hidable based on hidden property.
Toolbar [json](https://paste.fedoraproject.org/413324/46446147/) to reproduce
Old way:
selection_059

EDIT: if toolbar list does not contain any visible items, make whole list invisible.

### CODE REVIEW

**Comment by karelhala** [comment]
If @jzigmund is happy with the outcome we can merge it and it will be available in next release of ui-components.

**Comment by karelhala** [comment]
@jzigmund okay, changed it to not display any toolbar list if no items inside toolbar list is visible.

**Comment by mtho11** [comment]
LGTM.

**Comment by mtho11** [comment]
Available in v0.0.5

**Pull request merged**
