### PR TITLE
[WIP] Integrating Embedded Workflow options in Add Dialog- initial changes

### PR DESCRIPTION
**Pull request by noopurAg**
https://user-images.githubusercontent.com/52702093/233608528-877cd3bf-2a35-41e8-82c4-fb5ed7b9dfc0.mov

### CODE REVIEW

**Comment by noopurAg** [comment]
image
image

**Comment by Fryguy** [comment]
The backend to store these values is completed, so this can move forward.  cc @agrare @jeffibm

**Comment by Fryguy** [comment]
@noopurAg Can this be closed since we merged https://github.com/ManageIQ/ui-components/pull/471?

**Comment by noopurAg** [comment]
yes , closing this.

**Pull request closed without merging**
