### PR TITLE
Fix Dialog Editor styling issues

### PR DESCRIPTION
**Pull request by epwinchell**
This PR is a follow-up to https://github.com/ManageIQ/manageiq-ui-classic/pull/3668 and addresses the following requests:

-  correctly applies form-horizontal class for label positioning
-  decrease size of label column 
-  increase size of text area
-  decrease size of dropdowns
-  move refresh button below text area

https://bugzilla.redhat.com/show_bug.cgi?id=1553697

Old (Classic UI)
screen shot 2018-03-27 at 2 22 15 pm

New (Classic UI)
screen shot 2018-03-27 at 2 20 51 pm

Old (Classic UI)
screen shot 2018-05-02 at 12 55 48 pm

New (Classic UI)
screen shot 2018-05-03 at 10 25 26 am

Old (Service UI)
screen shot 2018-04-11 at 1 38 03 pm

New (Service UI)
screen shot 2018-04-11 at 1 07 21 pm

### CODE REVIEW

**Comment by epwinchell** [comment]
@miq-bot add_label bug, gaprindashvili/yes

**Comment by epwinchell** [comment]
@miq-bot assign @himdel

**Comment by epwinchell** [comment]
@himdel this one needs to be tested in classic.

**Comment by himdel** [comment]
Unless we want 4 extra empty divs for each field element, those `ng-switch-when` need to move on the new divs.

Otherwise, you'll get

```
<div class="col-sm-4"> (naah, empty, not a DialogFieldTextBox)
</div>

<div class="col-sm-8"> (not a DialogFieldTextAreaBox either)
</div>

... etc
```

And then suddenly you switch from

```
  .col-sm-4
    [ng-switch-when]
```

to

```
    <div ng-switch-when="DialogFieldCheckBox">
      <div class="col-sm-4">
```

(so reverse order).

This needs some consistency.

**Comment by himdel** [comment]
(Replaced by https://github.com/ManageIQ/ui-components/pull/293)

**Pull request closed without merging**
