### PR TITLE
Clicking on order button will call only button function and not row click function

### PR DESCRIPTION
**Pull request by karelhala**
### Fixes clicking on button in GTL calls click on row
When clicking on button inside tile it will also call on row click. This PR fixes such issue and only triggers button click call.

### BZ
https://bugzilla.redhat.com/show_bug.cgi?id=1518443

### CODE REVIEW

**Comment by martinpovolny** [comment]
Code looks good, tests look great, have not tested this though.

Ping @h-kataria ?

**Comment by h-kataria** [comment]
verified fix in UI. @martinpovolny please merge.

**Comment by martinpovolny** [comment]
@himdel, @simaishi : we will need another release for the next build of Gaprindashvili. Thank you!

**Comment by himdel** [comment]
When is the next build? Do we need the release now, or do we wait for the other `gaprindashvili/yes` PR?

(I've updated the others to say `gaprindashvili/backported`, since 1.0.1 is in.)

**Comment by martinpovolny** [comment]
@himdel: normally a build is scheduled every Tuesday. So please, cut a release and have a PR merged with deps in the Gaprindashvili branch by then. Thx!

**Comment by himdel** [comment]
@miq-bot add_label gaprindashvili/backported
@miq-bot remove_label gaprindashvili/yes

This was released in manageiq-ui-components 1.0.2, backported to gaprindashvili via https://github.com/ManageIQ/manageiq-ui-classic/pull/2951.

**Pull request merged**
