### PR TITLE
Renamed Dialog component and got help icon implemented

### PR DESCRIPTION
**Pull request by chalettu**
Renamed dialog component to dialog-user.  Also got the functionality implemented for tooltips if a description exists for a dialog field. 
PV https://www.pivotaltracker.com/n/projects/1914499/stories/146312871

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label enhancement
@miq-bot add_label ux/review

**Comment by chalettu** [comment]
Demo of the info icon in action 
fixed position

**Comment by chalettu** [comment]
@himdel , this is the PR that we discussed about renaming the component and also adding the info icon.

**Comment by serenamarie125** [comment]
@Loicavenel I was under the impression that we needed a new database field for field level help, did I misunderstand?

**Comment by chriskacerguis** [comment]
@serenamarie125 we were able to use an existing field for the info (so no db or API changes were needed)

**Comment by serenamarie125** [comment]
@chriskacerguis i'm not sure which field you used, but when speaking with @loicavenel we were talking about this having a new field.  I'm assuming you may be using the description field, which is currently shown as a tooltip.  I don't think it will be intuitive for dialog authors to realize that the description will be used in this manner, although I do appreciate that it will be a quicker way to release this.  Let's wait for Loic

**Comment by chriskacerguis** [comment]
:+1:

**Comment by Loicavenel** [comment]
I do agree,  of we renamed Description like "Help Message" or we add a new field..
Adding a new field is easier for exsiting customer, @dclarizio I am not sure this was already scoped on your side but this was part of the next release discussion, this looks like a small effort, adding a new field in the DB and updading he editor for it.
@chriskacerguis Do you need a change on the API to get this extra data?
@gmcculloug for you information.

**Comment by chriskacerguis** [comment]
@Loicavenel yes we would need an additional data returned, I'll update the API req. deck

**Comment by serenamarie125** [comment]
@chriskacerguis please consider naming it something more like "field level help" so it's easy to connect. Thanks!

**Comment by chalettu** [comment]
I am going to close this PR out until we get the API changes put in place.  Will open a new one for the component name change

**Pull request closed without merging**
