### PR TITLE
Add right margin to toolbar button icons

### PR DESCRIPTION
**Pull request by petervo**
Matches margin used in toolbarList buttons

### CODE REVIEW

**Comment by martinpovolny** [comment]
ping @epwinchell

**Comment by epwinchell** [comment]
@petervo Let's avoid inline styling. For the time being, toolbar styling is still handled here: https://github.com/ManageIQ/manageiq/blob/master/app/assets/stylesheets/patternfly_overrides.scss#L388

**Comment by petervo** [comment]
Just copying the current implementation.

https://github.com/ManageIQ/ui-components/blob/master/src/toolbar/components/toolbar-menu/toolbar-list.html#L4

But feel free to close and fix however you prefer. It just doesn't look great right now.

**Comment by epwinchell** [comment]
@petervo Please include a screenshot. Thanks

**Comment by himdel** [comment]
So, @petervo this only affects first-level buttons, right?

What I'm seeing is that buttons with text do look better...

before

ui37z

after

ui37y


But buttons without any text look worse...

before

ui37x

after

ui37


Care to fix? :)

**Comment by petervo** [comment]
@himdel, yep good point. Fixed, but as @epwinchell said it's probably better / more correct to use css selectors or classes for this but i don't really have time to dig into that right now. So feel free to close and fix another way if this is too hacky.

**Comment by himdel** [comment]
@petervo I'd definitely have preferred css classes but.. well, this is still better and you're right that it's not the only inline style we need to fix there.

So .. merging .. and creating an refactoring issue :)

Thanks

**Pull request merged**
