### PR TITLE
Fix at-loader failures in specs

### PR DESCRIPTION
**Pull request by himdel**
Fixes https://travis-ci.com/github/ManageIQ/ui-components/builds/182803973

    ERROR in [at-loader] ./node_modules/@types/lodash/common/common.d.ts:12:20
    TS2370: A rest parameter must be of an array type.

    ERROR in [at-loader] ./node_modules/@types/lodash/common/common.d.ts:255:22
    TS2304: Cannot find name 'unknown'.

    ERROR in [at-loader] ./node_modules/@types/lodash/common/function.d.ts:562:38
    TS2304: Cannot find name 'Parameters'.

(211 errors)

These seem to be caused by newer versions of lodash not conforming to the ancient `@types/lodash` schema.
Since `@types/` repos are obsolete and removing it fixes the problem, doing that.

### CODE REVIEW

**Comment by himdel** [comment]
ah, Cc @h-kataria  :)

**Comment by simaishi** [comment]
@himdel Travis is failing in jansa/ivanchuk branches as well. Can this be `jansa/yes` and `ivanchuk/yes`?

**Comment by himdel** [comment]
@simaishi Ah, thanks, yes, this should work in both branches :) Added

**Comment by simaishi** [comment]
Jansa backport details:

```
$ git log -1
commit 830770954ad7e19c9a5fc116e58c36ed7d49b953
Author: Harpreet Kataria <hkataria@redhat.com>
Date:   Wed Sep 9 16:11:37 2020 -0400

    Merge pull request #450 from himdel/fix-travis

    Fix at-loader failures in specs

    (cherry picked from commit e61f8d394508f4033e8cfb3b4d0e39fada7779bf)
```

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 140c1e01820d3dceda438ef632874eab39597c46
Author: Harpreet Kataria <hkataria@redhat.com>
Date:   Wed Sep 9 16:11:37 2020 -0400

    Merge pull request #450 from himdel/fix-travis

    Fix at-loader failures in specs

    (cherry picked from commit e61f8d394508f4033e8cfb3b4d0e39fada7779bf)
```

**Pull request merged**
