### PR TITLE
ToolbarView - update html to match patternfly 3.10

### PR DESCRIPTION
**Pull request by himdel**
Without this, all the view toolbar items are blue, all the time, as of ManageIQ/manageiq#11020

Updated the view toolbar to match https://www.patternfly.org/pattern-library/content-views/list-view/

Cc: @karelhala, @skateman, @martinpovolny 

You can test by doing `bower install manageiq-ui-components=himdel/ui-components#fix-pf-310` under `manageiq/`

### CODE REVIEW

**Comment by skateman** [comment]
Verified fix! :+1:

**Comment by karelhala** [comment]
@himdel looks good! Much better than using `<ul>` and `<li>` could you try running `npm t` to see if test are fine? Looks like `toolbarViewComponent.spec.ts:42` should be changed to expect buttons.

**Comment by himdel** [comment]
Updated the specs, now they seem to pass :)

**Comment by himdel** [comment]
Released 0.0.7..

**Pull request merged**
