### PR TITLE
Use the external DialogEditorHttpService for retrieving categories

### PR DESCRIPTION
**Pull request by skateman**
We do not want to depend on any specific API in this repo, the preferred way is to use a service that does these things externally.

Original idea: https://github.com/ManageIQ/manageiq-ui-classic/pull/3414 and https://github.com/ManageIQ/ui-components/issues/219
Depends on: https://github.com/ManageIQ/manageiq-ui-classic/pull/3426

@miq-bot assign @romanblanco

### CODE REVIEW

**Comment by skateman** [comment]
@miq-bot assign @karelhala

**Comment by eclarizio** [comment]
@miq-bot add_label gaprindashvili/yes

Please see comment in https://github.com/ManageIQ/manageiq-ui-classic/pull/3426 about why this now needs to be backported to gaprindashvili.

**Comment by himdel** [comment]
Backported to gaprindashvili:

```
commit 1cea4b26450b321162b16437fc74e69cf56d9759 (HEAD -> gaprindashvili)
Author: Karel Hala <ch4rlien@gmail.com>
Date:   Wed Feb 21 16:43:38 2018 +0100

    Merge pull request #262 from skateman/resolve-categories-http-service
    
    Use the external DialogEditorHttpService for retrieving categories
    
    (cherry picked from commit db05e8c0ea8b0703688d62481af60c4bdc4eb91c)
```

@miq-bot add_label gaprindashvili/backported
@miq-bot remove_label gaprindashvili/yes

**Comment by himdel** [comment]
Released in 1.0.26

**Comment by eclarizio** [comment]
@himdel Hey Martin, since you're available, do you mind commenting on https://github.com/ManageIQ/manageiq-ui-classic/pull/3426 and https://github.com/ManageIQ/manageiq-ui-classic/pull/3414 if you think those are good to go as well? I think David is gone for the day and we want to get those in to complement the ui-components changes.

**Pull request merged**
