### PR TITLE
Allow to parse a string with a floating point number

### PR DESCRIPTION
**Pull request by romanblanco**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1600007

replacing `parseInt()` with `parseFloat()` to allow to parse a string with a floating point number

### CODE REVIEW

**Comment by romanblanco** [comment]
@miq-bot add_label gaprindashvili/yes, bug

**Comment by romanblanco** [comment]
@chalettu please review

**Comment by romanblanco** [comment]
@himdel thanks, corrected

**Comment by himdel** [comment]
LGTM :+1: 

I still think the type should be more explicitly set so that we can never treat number-like strings as numbers, but that's an entirely separate issue now :).

**Comment by himdel** [comment]
Backported to gaprindashvili:

```
commit 9ac870719a538896547d16a0e8bb27d0f2f02bdb
Author: Martin Hradil <himdel@seznam.cz>
Date:   Tue Jul 24 14:06:33 2018 +0100

    Merge pull request #319 from romanblanco/bz1600007
    
    Allow to parse a string with a floating point number
    
    (cherry picked from commit 327eb201217a808c89c267766682af58d620f3e5)
```

@miq-bot add_label gaprindashvili/backported
@miq-bot remove_label gaprindashvili/yes

**Comment by ZitaNemeckova** [comment]
Released in v1.0.33
https://github.com/ManageIQ/manageiq-ui-service/pull/1464
https://github.com/ManageIQ/manageiq-ui-classic/pull/4352

**Pull request merged**
